import json

SEED_RESOURCES = [
    # ── Task 2: sentence patterns ──────────────────────────────────────────
    {
        "resource_id": "seed-001",
        "type": "pattern",
        "name": "让步转折句",
        "zh_goal": "先承认对立观点，再转回自己立场，显示思维深度",
        "pattern": "While it is true that [对方观点], [自己立场] because [核心理由].",
        "items_json": json.dumps([
            "While it is true that technology has improved our lives, over-reliance on it may undermine human creativity.",
            "While it is undeniable that economic growth is important, environmental protection should take priority.",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["general", "argumentation"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "discussion", "both_views"]),
        "difficulty": "6.5",
        "common_errors_json": json.dumps([
            "While 引导让步从句后，主句不能再用 but",
            "concession 部分太长会导致重心偏移，建议不超过 15 词",
        ]),
    },
    {
        "resource_id": "seed-002",
        "type": "pattern",
        "name": "三步因果链句",
        "zh_goal": "用三步因果链推进论点，使论证有层次、有说服力",
        "pattern": "[A] leads to [B], which in turn [causes / results in] [C].",
        "items_json": json.dumps([
            "A sedentary lifestyle leads to weight gain, which in turn increases the risk of heart disease.",
            "Job automation leads to unemployment, which in turn widens the wealth gap in society.",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["general", "argumentation"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["problem_solution", "opinion", "discussion"]),
        "difficulty": "6.5",
        "common_errors_json": json.dumps([
            "两个 which 连用会使句子过于复杂，考官难以追踪逻辑",
            "因果关系必须逻辑自洽，不能强行串联不相关的概念",
        ]),
    },
    {
        "resource_id": "seed-014",
        "type": "pattern",
        "name": "对比转折句",
        "zh_goal": "在同一句中对比两个不同主体或现象，Task 1 和 Task 2 均可用",
        "pattern": "While [A] [verb phrase], [B], by contrast, [verb phrase].",
        "items_json": json.dumps([
            "While developed countries have reduced carbon emissions, developing nations continue to see rapid growth in fossil fuel use.",
            "While urban areas boast excellent public transport, rural communities often lack basic connectivity.",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["general", "comparison"]),
        "task_types_json": json.dumps(["task1", "task2"]),
        "question_types_json": json.dumps(["discussion", "opinion", "both_views", "line_graph", "bar_chart"]),
        "difficulty": "6.5",
        "common_errors_json": json.dumps([
            "While 引导让步从句，主句不能再加 but（二者选一）",
            "by contrast 和 in contrast 意思相同，不要在同一句中两个都用",
        ]),
    },

    # ── Task 2: functional expressions ────────────────────────────────────
    {
        "resource_id": "seed-003",
        "type": "expression",
        "name": "举例引入套句",
        "zh_goal": "引入具体例子支撑论点，比 'for example' 更学术化",
        "pattern": "",
        "items_json": json.dumps([
            "A case in point is [具体例子].",
            "This is exemplified by [现象或数据].",
            "A prime example of this can be seen in [领域或现象].",
            "To illustrate, [具体例子].",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["general"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "discussion", "problem_solution", "both_views"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "例子太笼统（如'在很多国家'），考官无法判断你是否真的理解",
            "举例后忘记链接回主论点，段落显得悬空",
        ]),
    },
    {
        "resource_id": "seed-004",
        "type": "expression",
        "name": "表达结果和影响套句",
        "zh_goal": "描述某行为或现象带来的后果，替换口语化的 'so' 或 'this causes'",
        "pattern": "",
        "items_json": json.dumps([
            "This has led to [结果].",
            "As a direct result of this, [结果].",
            "The consequence of [原因] is that [结果].",
            "This inevitably results in [结果].",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["general"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "discussion", "problem_solution"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "lead to 后接名词/动名词，不接 that 从句（'lead to that...' 错误）",
            "result in 和 result from 方向相反：in=导致，from=源于",
        ]),
    },
    {
        "resource_id": "seed-005",
        "type": "expression",
        "name": "表达个人立场套句",
        "zh_goal": "用学术化方式引出观点，替换口语化的 'I think'",
        "pattern": "",
        "items_json": json.dumps([
            "From my perspective, [观点].",
            "It is my contention that [观点].",
            "I would argue that [观点].",
            "There is no denying that [事实或观点].",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["general"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "both_views"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "同一篇文章重复使用同一套句会显得单调，注意多样化",
            "'I think / I believe' 过于口语化，正式写作中尽量回避",
        ]),
    },
    {
        "resource_id": "seed-015",
        "type": "expression",
        "name": "对策建议套句",
        "zh_goal": "在 Problem-Solution 题中提出建议，替换单调的 'should'",
        "pattern": "",
        "items_json": json.dumps([
            "Governments could tackle this issue by [具体措施].",
            "One effective approach would be to [措施].",
            "A more sustainable solution lies in [方向].",
            "It is imperative that [主语] [原形动词] [措施].",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["general", "problem_solution"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["problem_solution"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "'It is imperative that' 后接虚拟语气（原形动词），不加 should",
            "方案要具体可操作，避免 'the government should do more' 这类空话",
        ]),
    },

    # ── Task 2: collocations ───────────────────────────────────────────────
    {
        "resource_id": "seed-006",
        "type": "collocation",
        "name": "环境话题核心词块",
        "zh_goal": "环境类题目必备搭配，替换简单的 'pollution' 和 'the environment'",
        "pattern": "",
        "items_json": json.dumps([
            "carbon emissions（碳排放）",
            "fossil fuels（化石燃料）",
            "renewable energy（可再生能源）",
            "sustainable development（可持续发展）",
            "greenhouse gases（温室气体）",
            "ecological footprint（生态足迹）",
            "biodiversity loss（生物多样性丧失）",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["environment", "climate"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "problem_solution", "discussion"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "'environment' 是名词，'environmental' 是形容词，不可混用",
            "'pollution problem' 是冗余表达，直接用 'pollution' 即可",
        ]),
    },
    {
        "resource_id": "seed-007",
        "type": "collocation",
        "name": "教育话题核心词块",
        "zh_goal": "教育类题目必备搭配，提升词汇精准度和学术感",
        "pattern": "",
        "items_json": json.dumps([
            "critical thinking（批判性思维）",
            "academic performance（学业表现）",
            "lifelong learning（终身学习）",
            "extracurricular activities（课外活动）",
            "vocational training（职业培训）",
            "higher education（高等教育）",
            "educational attainment（受教育程度）",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["education"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "discussion", "problem_solution"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "'knowledge' 通常不可数，不能说 'a knowledge'",
            "注意区分 'study' (动词/名词) 和 'education' (制度/过程)",
        ]),
    },
    {
        "resource_id": "seed-008",
        "type": "collocation",
        "name": "科技话题核心词块",
        "zh_goal": "科技类题目必备搭配，快速提升学术词汇密度",
        "pattern": "",
        "items_json": json.dumps([
            "artificial intelligence（人工智能）",
            "digital literacy（数字素养）",
            "technological advancement（技术进步）",
            "automation（自动化）",
            "data privacy（数据隐私）",
            "social media（社交媒体）",
            "screen time（屏幕时间）",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["technology"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "discussion", "problem_solution"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "'internet' 一般小写，除非特指正式文件中的专有名词",
            "'technology' 为不可数名词，'technologies' 指多种具体技术",
        ]),
    },

    # ── Task 2: logic templates ───────────────────────────────────────────
    {
        "resource_id": "seed-012",
        "type": "logic_template",
        "name": "观点题段落逻辑链（PEEL）",
        "zh_goal": "Opinion / Agree-Disagree 题的标准段落推进结构",
        "pattern": "Point → Explain → Example → Link back",
        "items_json": json.dumps([]),
        "zh_logic_chain_json": json.dumps([
            "1. Point：直接说明本段核心立场",
            "2. Explain：解释为什么（原因/机制），1-2 句",
            "3. Example：用具体例子或数据支撑，尽量具体",
            "4. Link back：把例子和开头论点挂钩，不要只是复述例子",
        ]),
        "topic_tags_json": json.dumps(["general", "argumentation"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["opinion", "both_views"]),
        "difficulty": "6.5",
        "common_errors_json": json.dumps([
            "缺少 Link back 句，段落显得悬空，考官会认为你没有论证清楚",
            "举例太笼统（如'在很多国家'），需要更具体的细节",
        ]),
    },
    {
        "resource_id": "seed-013",
        "type": "logic_template",
        "name": "问题解决题逻辑链",
        "zh_goal": "Problems & Solutions 题的标准段落推进结构",
        "pattern": "Problem → Cause → Solution → Expected Benefit",
        "items_json": json.dumps([]),
        "zh_logic_chain_json": json.dumps([
            "1. 点出问题：说明该社会问题的现状或危害（1-2 句）",
            "2. 分析原因：1-2 个核心原因，不要列举过多",
            "3. 提出方案：政府 / 个人 / 企业各出一招，方案要具体",
            "4. 预期效果：说明方案落实后能带来什么改变（不要只列举方案）",
        ]),
        "topic_tags_json": json.dumps(["general", "problem_solution"]),
        "task_types_json": json.dumps(["task2"]),
        "question_types_json": json.dumps(["problem_solution"]),
        "difficulty": "6.5",
        "common_errors_json": json.dumps([
            "方案太泛，如'政府应该做更多'，考官看不出你有真实想法",
            "只列方案、忘说预期效果，段落逻辑不完整",
        ]),
    },

    # ── Task 1: patterns ──────────────────────────────────────────────────
    {
        "resource_id": "seed-009",
        "type": "pattern",
        "name": "Task 1 总体趋势句（Overall）",
        "zh_goal": "Task 1 必写 Overall 段的核心句型，不写 Overall 是最常见扣分项",
        "pattern": "Overall, [subject] experienced a [significant / gradual / steady] [increase / decrease] from [X] to [Y].",
        "items_json": json.dumps([
            "Overall, the number of international students experienced a significant rise from 2000 to 2020.",
            "Overall, car ownership saw a steady increase over the 30-year period.",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["line_graph", "bar_chart", "trend"]),
        "task_types_json": json.dumps(["task1"]),
        "question_types_json": json.dumps(["line_graph", "bar_chart", "table"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "Overall 后需加逗号（Overall, ...）",
            "Task 1 不写 Overall 段，据考官反馈是最常见失分原因之一",
        ]),
    },
    {
        "resource_id": "seed-010",
        "type": "pattern",
        "name": "Task 1 峰值低谷句",
        "zh_goal": "精准描述折线图或柱图的最高点和最低点",
        "pattern": "[Subject] peaked at [数值] in [year], before [falling / declining] to [数值] by [year].",
        "items_json": json.dumps([
            "Sales peaked at 500 units in 2015, before declining to 320 units by 2018.",
            "The unemployment rate hit a low of 3.2% in 2019, rising sharply to 8.1% by 2020.",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["line_graph", "bar_chart"]),
        "task_types_json": json.dumps(["task1"]),
        "question_types_json": json.dumps(["line_graph", "bar_chart"]),
        "difficulty": "6.5",
        "common_errors_json": json.dumps([
            "'peaked at'（不是 peaked to），at 后面接具体数值",
            "'hit a peak' 和 'peaked at' 意思相同，不要在同一段落重复使用",
        ]),
    },
    {
        "resource_id": "seed-011",
        "type": "pattern",
        "name": "Task 1 比例描述句",
        "zh_goal": "描述饼图或表格中各部分的占比，替换简单的 'X is the biggest'",
        "pattern": "[X] accounted for the [largest / smallest] share of [total], at [数值]%.",
        "items_json": json.dumps([
            "Housing accounted for the largest share of household expenditure, at 35%.",
            "Transport represented the smallest proportion of the budget, making up only 8%.",
        ]),
        "zh_logic_chain_json": json.dumps([]),
        "topic_tags_json": json.dumps(["pie_chart", "table", "proportion"]),
        "task_types_json": json.dumps(["task1"]),
        "question_types_json": json.dumps(["pie_chart", "table", "bar_chart"]),
        "difficulty": "6.0",
        "common_errors_json": json.dumps([
            "'accounted for' 后直接接百分比（不加 'as'）",
            "proportion / percentage / share 意思相近但搭配略有不同，不要混用",
        ]),
    },
]
